




CREATE TABLE PERSON (
		ID SERIAL
	, FIRST_NAME VARCHAR(128) NOT NULL
	, LAST_NAME VARCHAR(128) NOT NULL
	, BIRTHDAY DATE
	, NICKNAME VARCHAR(128) NOT NULL
	, PHOTO VARCHAR(128)
	, UNIQUE UQ_PERSON_1 (NICKNAME)

);


CREATE TABLE USER (
		ID SERIAL
	, LOGIN VARCHAR(32) NOT NULL
	, PASSWORD VARCHAR(32) NOT NULL
	, EMAIL VARCHAR(128) NOT NULL
	, PERSON_ID BIGINT UNSIGNED
	, UNIQUE KEY UQ_USER_1 (LOGIN)
	, CONSTRAINT FK_USER_1 FOREIGN KEY (PERSON_ID)
REFERENCES PERSON (ID) ON DELETE CASCADE
);

CREATE TABLE FRIENDSHIP (
		PERSON_ID BIGINT UNSIGNED
	, FRIEND_ID BIGINT UNSIGNED
	, FRIENDSHIP_DATE DATE
	, PRIMARY KEY (PERSON_ID, FRIEND_ID)
	, CONSTRAINT FK_FRIENDSHIP_1 FOREIGN KEY (PERSON_ID)
REFERENCES PERSON (ID) ON DELETE CASCADE
	, CONSTRAINT FK_FRIENDSHIP_2 FOREIGN KEY (FRIEND_ID)
REFERENCES PERSON (ID) ON DELETE CASCADE
);

CREATE TABLE HOBBY (
		ID serial
	, TITLE VARCHAR(128)
	, DESCRIPTION VARCHAR(255)
);

CREATE TABLE MESSAGE (
		ID SERIAL
	, CONTENT VARCHAR(512) NOT NULL
	, TIME_SENT TIMESTAMP NOT NULL
	, ID_PERSON_FROM BIGINT UNSIGNED
	, ID_PERSON_TO BIGINT UNSIGNED
	, CONSTRAINT FK_MESSAGE_1 FOREIGN KEY (ID_PERSON_FROM)
REFERENCES PERSON (ID) ON DELETE CASCADE
	, CONSTRAINT FK_MESSAGE_2 FOREIGN KEY (ID_PERSON_TO)
REFERENCES PERSON (ID) ON DELETE CASCADE
);

CREATE TABLE PLACE (
		ID SERIAL
	, TITLE VARCHAR(128) NOT NULL
	, DESCRIPTION VARCHAR(255) NOT NULL
	, LATITUDE DECIMAL(10, 6)
	, LONGITUDE DECIMAL(10, 6)
);

CREATE TABLE POST (
		ID SERIAL
	, TITLE VARCHAR(128) NOT NULL
	, CONTENT VARCHAR(255) NOT NULL
	, PLACE_TIME TIMESTAMP NOT NULL
	, OWNER_ID BIGINT UNSIGNED
	, CONSTRAINT FK_POST_1 FOREIGN KEY (OWNER_ID)
REFERENCES PERSON (ID) ON DELETE CASCADE

);
CREATE TABLE POST_LIKES (
		PERSON_ID BIGINT UNSIGNED
	, POST_ID BIGINT UNSIGNED
	, PRIMARY KEY (PERSON_ID, POST_ID)
	, CONSTRAINT FK_POST_LIKES_1 FOREIGN KEY (PERSON_ID)
REFERENCES PERSON (ID) ON DELETE CASCADE
	, CONSTRAINT FK_POST_LIKES_2 FOREIGN KEY (POST_ID)
REFERENCES POST (ID) ON DELETE CASCADE
);

CREATE TABLE PERSON_PLACE (
		PERSON_ID BIGINT UNSIGNED
	, PLACE_ID BIGINT UNSIGNED
	, PRIMARY KEY (PERSON_ID, PLACE_ID)
	, CONSTRAINT FK_PERSON_PLACE_1 FOREIGN KEY (PERSON_ID)
REFERENCES PERSON (ID) ON DELETE CASCADE
	, CONSTRAINT FK_PERSON_PLACE_2 FOREIGN KEY (PLACE_ID)
REFERENCES PLACE (ID) ON DELETE CASCADE
);

CREATE TABLE PERSON_HOBBY (
		PERSON_ID BIGINT UNSIGNED
	, HOBBY_ID BIGINT UNSIGNED
	, PRIMARY KEY (PERSON_ID, HOBBY_ID)
	, CONSTRAINT FK_PERSON_HOBBY_1 FOREIGN KEY (PERSON_ID)
REFERENCES PERSON (ID) ON DELETE CASCADE
	, CONSTRAINT FK_PERSON_HOBBY_2 FOREIGN KEY (HOBBY_ID)
REFERENCES HOBBY (ID) ON DELETE CASCADE
);