INSERT INTO PERSON (ID, FIRST_NAME, LAST_NAME, BIRTHDAY, NICKNAME) VALUES (1, 'Barry', 'Alen', '1978-11-11','Flash');
INSERT INTO PERSON (ID, FIRST_NAME, LAST_NAME, BIRTHDAY, NICKNAME) VALUES (2, 'Wally', 'West', '1998-12-12','Kid Flash');
INSERT INTO PERSON (ID, FIRST_NAME, LAST_NAME, BIRTHDAY, NICKNAME) VALUES (3, 'Iris', 'West-Alen', '1998-12-12','Barry Wife');

INSERT INTO FRIENDSHIP (PERSON_ID, FRIEND_ID, FRIENDSHIP_DATE) VALUES (1, 2,'2015-01-01');
INSERT INTO FRIENDSHIP (PERSON_ID, FRIEND_ID, FRIENDSHIP_DATE) VALUES (1, 3,'1990-01-01');

INSERT INTO HOBBY (TITLE, DESCRIPTION) VALUES ('jogging', 'run across whole town');
INSERT INTO HOBBY (TITLE, DESCRIPTION) VALUES ('crying', 'complain for every reason');

INSERT INTO MESSAGE (CONTENT, ID_PERSON_FROM, ID_PERSON_TO) VALUES ('i love you', 1, 3);
INSERT INTO MESSAGE (CONTENT, ID_PERSON_FROM, ID_PERSON_TO) VALUES ('lets go', 1, 2);

INSERT INTO PLACE (TITLE, DESCRIPTION, LATITUDE, LONGITUDE) VALUES ('house','big house', 11.111111, 11.111111);
INSERT INTO PLACE (TITLE, DESCRIPTION, LATITUDE, LONGITUDE) VALUES ('HQ', 'Star Labs', 22.222222, 22.222222);

INSERT INTO POST (TITLE, CONTENT, OWNER_ID) VALUES ('tits','tits is good', 1);
INSERT INTO POST (TITLE, CONTENT, OWNER_ID) VALUES ('martial arts','i know kung fu', 2);

INSERT INTO POST_LIKES (PERSON_ID, POST_ID) VALUES (3, 1);
INSERT INTO POST_LIKES (PERSON_ID, POST_ID) VALUES (3, 2);

INSERT INTO PERSON_HOBBY (PERSON_ID, HOBBY_ID) VALUES (1, 1);
INSERT INTO PERSON_HOBBY (PERSON_ID, HOBBY_ID) VALUES (2, 1);
INSERT INTO PERSON_HOBBY (PERSON_ID, HOBBY_ID) VALUES (1, 2);
INSERT INTO PERSON_HOBBY (PERSON_ID, HOBBY_ID) VALUES (3, 2);

INSERT INTO PERSON_PLACE (PERSON_ID, PLACE_ID) VALUES (3, 2);
INSERT INTO PERSON_PLACE (PERSON_ID, PLACE_ID) VALUES (1, 2);
INSERT INTO PERSON_PLACE (PERSON_ID, PLACE_ID) VALUES (2, 2);
INSERT INTO PERSON_PLACE (PERSON_ID, PLACE_ID) VALUES (1, 1);
INSERT INTO PERSON_PLACE (PERSON_ID, PLACE_ID) VALUES (3, 1);
